import type { Post } from '@/types'

const day = (offset: number) => new Date(Date.now() - offset * 86400000).toISOString()

export const seedPosts: Post[] = [
  {
    id: 'p-1',
    authorId: 'u-buddy',
    body: "Hey everyone, I'm Buddy 👀 — the campus assistant living inside Cohort. Ask me to find users, communities, or features. No promises about being nice about it.",
    createdAt: day(30),
    attachments: [],
    mentions: [],
    likeCount: 41,
    likedByMe: false,
    replies: [
      { id: 'r-1', postId: 'p-1', authorId: 'u-veerbhadra', body: 'okay buddy, find me the OWASP club', createdAt: day(29) },
    ],
  },
  {
    id: 'p-2',
    authorId: 'u-chirag',
    body: 'Welcome to Cohort! 🎉 A social platform built by students, for PCCOE students. Glad to have you here — @cohort is where we post updates.',
    createdAt: day(28),
    attachments: [],
    mentions: ['cohort'],
    likeCount: 87,
    likedByMe: true,
    replies: [],
  },
  {
    id: 'p-3',
    authorId: 'u-vrushabh',
    body: 'Messaging has arrived on Cohort 🔒 Encrypted 1:1 chats are live under Connect. Messages auto-disappear 30s after being read.',
    createdAt: day(21),
    attachments: [],
    mentions: [],
    likeCount: 63,
    likedByMe: false,
    replies: [
      { id: 'r-2', postId: 'p-3', authorId: 'u-shravan', body: 'finally! this is huge', createdAt: day(20) },
      { id: 'r-3', postId: 'p-3', authorId: 'u-isha', body: 'love the disappearing messages touch', createdAt: day(20) },
    ],
  },
  {
    id: 'p-4',
    authorId: 'u-anushka',
    body: 'Profile pictures are now customizable ✨ head to your profile and tap the camera icon on your avatar.',
    createdAt: day(17),
    attachments: [],
    mentions: [],
    likeCount: 35,
    likedByMe: false,
    replies: [],
  },
  {
    id: 'p-5',
    authorId: 'u-shravan',
    body: '@gdgcpccoe workshop tomorrow at 4 PM in Seminar Hall 2. Bring your laptops, we\'re building with Firebase.',
    createdAt: day(12),
    attachments: [],
    mentions: ['gdgcpccoe'],
    likeCount: 22,
    likedByMe: false,
    replies: [],
  },
  {
    id: 'p-6',
    authorId: 'u-buddy',
    body: 'New on Cohort: Arcade 🎮 Chess, Tic-Tac-Toe and Sudoku are live under the game controller icon. I play Black in chess, and yes I will castle on you.',
    createdAt: day(9),
    attachments: [],
    mentions: [],
    likeCount: 58,
    likedByMe: true,
    replies: [],
  },
  {
    id: 'p-7',
    authorId: 'u-om',
    body: 'Team Kratos Racing exam-solutions drive folder for Sem 5 Mechanical: https://drive.google.com/drive/folders/kratos-sem5-notes — organized by subject, feel free to add yours.',
    createdAt: day(7),
    attachments: [],
    mentions: [],
    likeCount: 44,
    likedByMe: false,
    replies: [],
  },
  {
    id: 'p-8',
    authorId: 'u-isha',
    body: 'You can now sync your LinkedIn certifications into your Flex 💼 Profile → Edit Profile → add your LinkedIn username.',
    createdAt: day(5),
    attachments: [],
    mentions: [],
    likeCount: 19,
    likedByMe: false,
    replies: [],
  },
  {
    id: 'p-9',
    authorId: 'u-chirag',
    body: "Check out the Marketplace 🛒 (coming soon — buy, sell and trade textbooks, gear, and more with fellow students).",
    createdAt: day(3),
    attachments: [],
    mentions: [],
    likeCount: 27,
    likedByMe: false,
    replies: [],
  },
  {
    id: 'p-10',
    authorId: 'u-veerbhadra',
    body: 'Good morning c/cohort ☀️ starting the week with a full battery and zero patience for 8 AM lectures.',
    createdAt: day(1),
    attachments: [],
    mentions: [],
    likeCount: 11,
    likedByMe: false,
    replies: [],
  },
]
