import type { AppUser } from '@/types'

export const seedUsers: AppUser[] = [
  {
    id: 'u-chirag',
    handle: 'chiragferwani',
    displayName: 'Chirag Ferwani',
    department: 'CSE(AIML)',
    role: 'admin',
    linkedinUsername: 'chiragferwani',
    email: 'chirag.ferwani24@pccoepune.org',
    bio: 'Building Cohort. Occasionally sleeps.',
    communitiesCount: 12,
    followersCount: 214,
    followingCount: 58,
    flexCount: 6,
  },
  {
    id: 'u-vrushabh',
    handle: 'vrushabhhirap',
    displayName: 'Vrushabh Hirap',
    department: 'Computer',
    role: 'admin',
    linkedinUsername: 'vrushabhhirap',
    email: 'vrushabh.hirap24@pccoepune.org',
    bio: 'Co-founder, Cohort. Ships things.',
    communitiesCount: 10,
    followersCount: 189,
    followingCount: 41,
    flexCount: 5,
  },
  {
    id: 'u-anushka',
    handle: 'anushkashinde',
    displayName: 'Anushka Shinde',
    department: 'IT',
    role: 'admin',
    linkedinUsername: 'anushkashinde',
    email: 'anushka.shinde24@pccoepune.org',
    bio: 'Co-founder, Cohort. Design + community.',
    communitiesCount: 9,
    followersCount: 176,
    followingCount: 63,
    flexCount: 4,
  },
  {
    id: 'u-buddy',
    handle: 'cohortbuddy',
    displayName: 'Buddy',
    department: 'COHORT Special',
    role: 'admin',
    bio: "Hey, I'm Buddy — your campus assistant for Cohort. I can search users, communities, and features live. No promises about being nice about it. 👀",
    communitiesCount: 1,
    followersCount: 410,
    followingCount: 1,
    flexCount: 0,
  },
  {
    id: 'u-shravan',
    handle: 'shravan24',
    displayName: 'Shravan Kulkarni',
    department: 'AIML Department',
    role: 'user',
    linkedinUsername: 'shravan-kulkarni',
    email: 'shravan.kulkarni24@pccoepune.org',
    bio: 'GDGC lead. Coffee-powered.',
    communitiesCount: 5,
    followersCount: 88,
    followingCount: 102,
    flexCount: 3,
  },
  {
    id: 'u-veerbhadra',
    handle: 'veerbhadra24',
    displayName: 'Veerbhadra Mahant',
    department: 'Computer Department',
    role: 'user',
    email: 'veerbhadra.mahant24@pccoepune.org',
    bio: 'Building stuff, breaking stuff, fixing stuff.',
    communitiesCount: 4,
    followersCount: 52,
    followingCount: 61,
    flexCount: 2,
  },
  {
    id: 'u-isha',
    handle: 'ishapatil',
    displayName: 'Isha Patil',
    department: 'ENTC Department',
    role: 'user',
    email: 'isha.patil24@pccoepune.org',
    bio: 'Art Circle. Sketches during lectures.',
    communitiesCount: 6,
    followersCount: 71,
    followingCount: 45,
    flexCount: 4,
  },
  {
    id: 'u-om',
    handle: 'omdeshmukh',
    displayName: 'Om Deshmukh',
    department: 'Mechanical Department',
    role: 'user',
    email: 'om.deshmukh24@pccoepune.org',
    bio: 'Team Kratos Racing. Loud pit stops.',
    communitiesCount: 3,
    followersCount: 39,
    followingCount: 28,
    flexCount: 1,
  },
]

export const DEMO_PERSONAS = ['u-veerbhadra', 'u-shravan', 'u-isha', 'u-om']

export function getUserById(id: string): AppUser | undefined {
  return seedUsers.find((u) => u.id === id)
}

export function getUserByHandle(handle: string): AppUser | undefined {
  return seedUsers.find((u) => u.handle === handle)
}
